modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CreeperHost/BackupManager/issues"
license = "BSD 4-Clause License"

[[mods]]
modId = "backupmanager"
version = "${version}"
displayName = "Backup Manager"
authors = "brandon3055, CreeperHost!"
description = '''
'''
#logoFile = ""

[[dependencies.backupmanager]]
modId = "neoforge"
type="required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "architectury"
type="required"
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "polylib"
type="required"
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "backupmanager-common.mixins.json"